## 베이즈 텍스트 분석

다루는 내용
--

- 메일이 스팸메일인지 아닌지 예측

데이터
--
- https://goo.gl/2WWtcs

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

데이터 읽기
--

In [2]:
sms = pd.read_csv('data/sms_spam.csv')
sms.head()

type                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
sms.shape

(5574, 2)

In [4]:
sms['type'].value_counts()

ham     4827
spam     747
Name: type, dtype: int64

In [5]:
sms_corpus = sms['text'] 

단어-벡터 생성
--

In [10]:
vectorizer = CountVectorizer(min_df=10) # 10번 이하로 발생한 단어 무시
X = vectorizer.fit_transform(sms_corpus)
X.shape

(5574, 1018)

In [25]:
y = sms['type'] 
y[:5]

0     ham
1     ham
2    spam
3     ham
4     ham
Name: type, dtype: object

In [24]:
X[:5].toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
X[:5].toarray().argmax(axis=1)

array([ 92, 462, 866, 731, 393])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X.toarray(), y, test_size=0.25)

베이즈 알고리즘 적용
--

In [27]:
clf = GaussianNB() 
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test).round(4))

0.8164


In [16]:
y_predict = clf.predict(X_test) 
print(metrics.classification_report(y_test, y_predict)) 

             precision    recall  f1-score   support

        ham       0.99      0.80      0.88      1227
       spam       0.39      0.94      0.55       167

avg / total       0.92      0.82      0.84      1394



In [29]:
print(metrics.confusion_matrix(y_test, y_predict))

[[981 246]
 [ 10 157]]
